name: Deploy React App to Vercel

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-deploy:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # 1. Checkout el código del repositorio
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # 3. Instalar dependencias
      - name: Install Dependencies
        run: |
          npm ci

      # 4. Ejecutar pruebas (opcional, puedes eliminar este paso si no tienes pruebas)
      #- name: Run Tests
      #  run: |
      #    yarn test --watchAll=false || echo "Tests failed" # Cambia a 'npm test' si usas npm

      # 5. Construir la aplicación
      - name: Build React App
        run: |
          npm run build --if-present

      # 6. Desplegar en Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
